export const SET_BICYCLES = 'SET_BICYCLES'
export const SET_BICYCLE = 'SET_BICYCLE'
export const ADD_BICYCLE = 'ADD_BICYCLE'
export const UPDATE_BICYCLE = 'UPDATE_BICYCLE'
export const DELETE_BICYCLE = 'DELETE_BICYCLE'
export const FETCH_BICYCLES_FAILED = 'FETCH_BICYCLES_FAILED'


